# Đọc dữ liệu

In [19]:
import pandas as pd

df = pd.read_csv("amazon.csv")
print(df.shape)
print(df.columns)
df.head()

(1465, 16)
Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

# Chọn những cột cần dùng

In [20]:
cols_needed = [
    "product_id",
    "product_name",
    "category",
    "discounted_price",
    "actual_price",
    "discount_percentage",
    "rating",
    "rating_count",
    "about_product",
    "img_link",
    "product_link"
]

df = df[cols_needed].copy()

# Ép kiểu về string và loại bỏ khoảng trắng

In [21]:
text_cols = ["product_id", "product_name", "category", "about_product", "img_link", "product_link"]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

# Hàm sử lí dữ liệu số

In [22]:
import numpy as np
import re

def clean_price(x):
    if pd.isna(x):
        return np.nan
    x = str(x).replace("₹", "").replace(",", "").strip()
    try:
        return float(x)
    except:
        return np.nan

def clean_percentage(x):
    if pd.isna(x):
        return np.nan
    x = str(x).replace("%", "").strip()
    try:
        return float(x)
    except:
        return np.nan

def clean_count(x):
    if pd.isna(x):
        return np.nan
    x = str(x).replace(",", "").strip()
    try:
        return int(float(x))
    except:
        return np.nan

def clean_rating(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    try:
        return float(x)
    except:
        return np.nan

In [23]:
df["discounted_price"] = df["discounted_price"].apply(clean_price)
df["actual_price"] = df["actual_price"].apply(clean_price)
df["discount_percentage"] = df["discount_percentage"].apply(clean_percentage)
df["rating"] = df["rating"].apply(clean_rating)
df["rating_count"] = df["rating_count"].apply(clean_count)

In [24]:
df = df[(df["rating"].isna()) | ((df["rating"] >= 0) & (df["rating"] <= 5))]
df = df[(df["discounted_price"].isna()) | (df["discounted_price"] >= 0)]
df = df[(df["actual_price"].isna()) | (df["actual_price"] >= 0)]
df = df[(df["rating_count"].isna()) | (df["rating_count"] >= 0)]

# Xử lí missing

In [25]:
df["product_name"] = df["product_name"].fillna("")
df["about_product"] = df["about_product"].fillna("")
df["category"] = df["category"].fillna("Unknown")
df["rating"] = df["rating"].fillna(df["rating"].median())
df["rating_count"] = df["rating_count"].fillna(0)

# Xử lí dữ liệu trùng

In [26]:
agg_dict = {
    "product_name": "first",
    "category": "first",
    "discounted_price": "first",
    "actual_price": "first",
    "discount_percentage": "first",
    "rating": "mean",
    "rating_count": "max",
    "about_product": "first",
    "img_link": "first",
    "product_link": "first"
}

df = df.groupby("product_id", as_index=False).agg(agg_dict)

# Phân cấp category

In [27]:
cat_split = df["category"].str.split("|", expand=True)

max_levels = cat_split.shape[1]
cat_split.columns = [f"cat_level_{i+1}" for i in range(max_levels)]

df = pd.concat([df, cat_split], axis=1)
df = df.rename(columns={"category": "category_path"})

# Điền dữ liệu thiếu cho các cấp category

In [28]:
for col in [c for c in df.columns if c.startswith("cat_level_")]:
    df[col] = df[col].fillna("Unknown")

# làm sạch text

In [29]:
def clean_text(text):
    text = str(text).lower()
    text = text.replace("&", " and ")
    text = text.replace("|", " ")
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [30]:
df["product_name_clean"] = df["product_name"].apply(clean_text)
df["about_product_clean"] = df["about_product"].apply(clean_text)
df["category_text"] = df["category_path"].apply(clean_text)

In [31]:
df["clean_text_no_category"] = (
    df["product_name_clean"] + " " + df["about_product_clean"]
)

In [32]:
df["clean_text_with_category"] = (
    df["product_name_clean"] + " " +
    df["about_product_clean"] + " " +
    df["category_text"]
)

In [33]:
df = df[df["product_name_clean"].str.len() > 5]
df = df[df["category_text"].str.len() > 2]

In [34]:
print(df.shape)
print(df.isna().sum())
df.head()

(1351, 23)
product_id                  0
product_name                0
category_path               0
discounted_price            0
actual_price                0
discount_percentage         0
rating                      0
rating_count                0
about_product               0
img_link                    0
product_link                0
cat_level_1                 0
cat_level_2                 0
cat_level_3                 0
cat_level_4                 0
cat_level_5                 0
cat_level_6                 0
cat_level_7                 0
product_name_clean          0
about_product_clean         0
category_text               0
clean_text_no_category      0
clean_text_with_category    0
dtype: int64

,product_id,product_name,category_path,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,img_link,...,cat_level_3,cat_level_4,cat_level_5,cat_level_6,cat_level_7,product_name_clean,about_product_clean,category_text,clean_text_no_category,clean_text_with_category
0,B002PD61Y4,D-Link DWA-131 300 Mbps Wireless Nano USB Adap...,Computers&Accessories|NetworkingDevices|Networ...,507.0,1208.0,58.0,4.1,8131.0,Connects your computer to a high-speed wireles...,https://m.media-amazon.com/images/I/31+NwZ8gb1...,...,NetworkAdapters,WirelessUSBAdapters,Unknown,Unknown,Unknown,d link dwa 131 300 mbps wireless nano usb adap...,connects your computer to a high speed wireles...,computers and accessories networkingdevices ne...,d link dwa 131 300 mbps wireless nano usb adap...,d link dwa 131 300 mbps wireless nano usb adap...
1,B002SZEOLG,TP-Link Nano USB WiFi Dongle 150Mbps High Gain...,Computers&Accessories|NetworkingDevices|Networ...,749.0,1339.0,44.0,4.2,179692.0,150 Mbps Wi-Fi —— Exceptional wireless speed u...,https://m.media-amazon.com/images/I/31Wb+A3VVd...,...,NetworkAdapters,WirelessUSBAdapters,Unknown,Unknown,Unknown,tp link nano usb wifi dongle 150mbps high gain...,150 mbps wi fi exceptional wireless speed up t...,computers and accessories networkingdevices ne...,tp link nano usb wifi dongle 150mbps high gain...,tp link nano usb wifi dongle 150mbps high gain...
2,B003B00484,Duracell Plus AAA Rechargeable Batteries (750 ...,Electronics|GeneralPurposeBatteries&BatteryCha...,399.0,499.0,20.0,4.3,27201.0,Duracell Rechargeable AAA 750mAh batteries sta...,https://m.media-amazon.com/images/I/418YrbHVLC...,...,RechargeableBatteries,Unknown,Unknown,Unknown,Unknown,duracell plus aaa rechargeable batteries 750 m...,duracell rechargeable aaa 750mah batteries sta...,electronics generalpurposebatteries and batter...,duracell plus aaa rechargeable batteries 750 m...,duracell plus aaa rechargeable batteries 750 m...
3,B003L62T7W,"Logitech B100 Wired USB Mouse, 3 yr Warranty, ...",Computers&Accessories|Accessories&Peripherals|...,279.0,375.0,26.0,4.3,31534.0,"A comfortable, ambidextrous shape feels good i...",https://m.media-amazon.com/images/I/31iFF1Kbkp...,...,"Keyboards,Mice&InputDevices",Mice,Unknown,Unknown,Unknown,logitech b100 wired usb mouse 3 yr warranty 80...,a comfortable ambidextrous shape feels good in...,computers and accessories accessories and peri...,logitech b100 wired usb mouse 3 yr warranty 80...,logitech b100 wired usb mouse 3 yr warranty 80...
4,B004IO5BMQ,"Logitech M235 Wireless Mouse, 1000 DPI Optical...",Computers&Accessories|Accessories&Peripherals|...,699.0,995.0,30.0,4.5,54405.0,You can surf the Web with more comfort and eas...,https://m.media-amazon.com/images/I/31CtVvtFt+...,...,"Keyboards,Mice&InputDevices",Mice,Unknown,Unknown,Unknown,logitech m235 wireless mouse 1000 dpi optical ...,you can surf the web with more comfort and eas...,computers and accessories accessories and peri...,logitech m235 wireless mouse 1000 dpi optical ...,logitech m235 wireless mouse 1000 dpi optical ...

In [35]:
df.to_csv("clean_products.csv", index=False, encoding="utf-8-sig")